# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
  - java -version
  - echo PATH=$PATH
  - echo JAVA_HOME=$JAVA_HOME
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo R CMD javareconf ; fi

matrix:
  include:
  - r: devel
  - r: release
  - r: release
    os: osx
    r_binary_packages: rJava
  - r: oldrel
  - r: 3.3
  - r: 3.2
  - r: 3.1
