# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

before_install:
  - java -version
  - echo PATH=$PATH
  - echo JAVA_HOME=$JAVA_HOME
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo R CMD javareconf ; fi

matrix:
  include:
  - r: devel
  - r: release
  - r: release
    os: osx
    # only install binaries on osx to avoid issues with rJava source install
    install:
    - R -e 'install.packages("remotes")'
    - R -e 'remotes::install_deps(dep = T, type = "binary")'
  - r: oldrel
  - r: 3.4
  - r: 3.3
  - r: 3.2
